require: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

RSpec/NoExpectationExample:
  Exclude:
    - spec/examples/**/*.rb
