[package]
name = "eunomia_gen"
version = "0.1.0"
edition = "2021"
authors = ["G Palmer <palmergs@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
